version: '3.1'

services:
  db:
    image: postgres:15
    container_name: forms-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: forms
      PGDATA: /var/lib/postgresql/data/
    volumes:
      - db:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    networks:
      - conn

  app:
    build: .
    container_name: forms-app
    ports:
      - 8080:8080
    depends_on:
      - db
    networks:
      - conn
volumes:
  db:

networks:
  conn:
    driver: bridge